In [1]:
import numpy as np
x = np.array([1,2,3,5])
N = 3
np.vander(x,N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [2]:
N=5
x = np.array([1,2,3,4,5])
np.column_stack([x**(N-1-i) for i in range(N)])

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [3]:
x = np.vander([1,2,3,4,5])

In [4]:
x

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [5]:
x = np.vander([1,2,3,4,5],increasing=True)
x

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

Write a function so that the columns of the output matrix are powers of the input
vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [6]:
N=5
x = np.array([1,2,3,4,5])
np.column_stack([x**i for i in range(N)])

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [7]:
import numpy as np
def vand(input_vector,n,increasing = False):
    if not increasing:
        output_matrix = np.array([x**(n-1-i) for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    elif increasing:
        output_matrix = np.array([x**(i) for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
        
    return output_matrix


n = 3
input_vector = np.array([1,2,3,4])
matrix_decreasing_order = vand(input_vector,n,False)
matrix_increasing_order = vand(input_vector,n,True)

print("-------output-------")
print("Vander matrix of the input array in decreasing order of powers:\n",matrix_decreasing_order,"\n")

print("Vander matrix of the input array in increasing order of powers:\n",matrix_increasing_order)

-------output-------
Vander matrix of the input array in decreasing order of powers:
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]] 

Vander matrix of the input array in increasing order of powers:
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]


##### Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Problem Statement

Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [8]:
import numpy as np

In [14]:
def moving_avg(a,n=3):
    result = np.cumsum(a,dtype='float')
    result[n:] = result[n:]-result[:-n]
    print(result)
    return result[n-1:]/n

a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
print(moving_avg(a,n=3))

[  3.   8.  15.  14.  17.  20.  29.  86. 148. 218. 252. 280. 349.]
[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
